import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./pages/Navbar";
import ChatBot from "./pages/FacultyChatbot";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "./pages/(auth)/Authcontext";
import FacultyBot from "./pages/Voice_assistent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          {/* Global Navbar */}
          <Navbar />

          {/* Toast notifications */}
          <Toaster />

          {/* Page Content */}
          {children}

          {/* Global Bots */}
          {/* FacultyBot */}
          <div className="fixed bottom-6 right-6 flex flex-row gap-5 z-50">
            <ChatBot />
            <FacultyBot userName="Nayan" userId="123" type="faculty" />
          </div>

          {/* Footer */}
          <footer className="flex justify-center mb-10 text-center  text-slate-600 text-sm">
            © {new Date().getFullYear()} Faculty & Class Management System. All
            rights reserved. Created By{" "}
            <span className="text-orange-300">Nayan Rajyaguru</span>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
